{
'name': 'Hospital Managemet',
'version': '1.0.0',
'sequence': -100,
'author': 'ahmed mohamud',
'website': 'www.ahmedmohamud.com',
'category': 'health',
'summary': 'hospital management system',
'description': 'hospital management system',
'depends': ['mail', 'product','web','base'],
'data': [
    'security/ir.model.access.csv',
    'data/patient_tag_data.xml',
    'data/patient.tag.csv',
    'data/sequence_data.xml',
    'data/mail_tempelate_data.xml',
    'wizard/cancel_appointment_view.xml',
    'views/odoo_playground_view.xml',
    'views/menu.xml',
    'views/patient_view.xml',
    'views/female_patient_view.xml',
    'views/male_patient_view.xml',
    'views/appointment_view.xml',
    'views/opreations_view.xml',
    'views/patient_tag.xml',
    'views/res_config_settings_views.xml',
    'report/patient_details_templete.xml',
    'report/report.xml',
    'report/patient_card.xml',

],
'demo': [],
'application':True,
'license': 'LGPL-3',

}
